language: generic 
sudo: required
services: 
  - docker

before_install: 
  - docker build -t benmcloughlin/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true benmcloughlin/docker-react npm run testD